### all weather realted data for Bonn
GET http://localhost:3001/bonn
### just weather status for Bonn
GET http://localhost:3001/weather/Melbourne
### cat facts
GET http://localhost:3001/
### temperature for bonn
GET http://localhost:3001/temp/Bonn